#DB Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=mysecretpassword
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/swimapp
quarkus.hibernate-orm.schema-management.strategy=validate

#Flyway
quarkus.flyway.migrate-at-start=true

#Swagger-UI
quarkus.smallrye-openapi.info-title=SwimApp
quarkus.smallrye-openapi.info-description=Swimming Management System
